// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yynluqboetyacksofplz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5bmx1cWJvZXR5YWNrc29mcGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMzAzODQsImV4cCI6MjA1MDkwNjM4NH0.qIuGMeJ4_jqGkdAhGhutw_y9jguwd8CI_7z2WO13vkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);